### ISSUE TITLE
'Wavefunction' object has no attribute 'freely_propagate'

### ISSUE THREAD

**Issue by duttapranab021** [savowe/pytalises#25]

**Comment by duttapranab021** [comment]
Every time I run the example code for Freely expanding 1D Gaussian wave packet it shows an error of  'Wavefunction' object has no attribute 'freely_propagate'

**Comment by savowe** [comment]
Could you plrease provide an exapt copy of the code you execute?

**Comment by duttapranab021** [comment]
![Capture](https://user-images.githubusercontent.com/62932240/109014099-d5b01680-76d9-11eb-8f34-0ca08f9c46c3.JPG)

**Comment by savowe** [comment]
It would be interesting to know which version you're using. Please run `pip list` or `pip3 list` and tell mich what version of pytalises is installed

**Comment by duttapranab021** [comment]
![Capture](https://user-images.githubusercontent.com/62932240/109024624-f4b3a600-76e3-11eb-94c5-b8d0f215e302.JPG)

**Comment by duttapranab021** [comment]
I am using python 3.7.3 version

**Comment by savowe** [comment]
Ok, thank you, that is very interesting. It seems to me that it currently downloads an older version of pytalises that does not have the functionality. The newest version is 0.2.7 (see [here](https://anaconda.org/conda-forge/pytalises/files)).
In 0.1.8 the freely propagate method does not work, but there are even worse bugs.
Can you please try
`pip install pytalises==0.2.7`
or
`conda install pytalises=0.2.7`
whether you are using pip or conda.
Thank you in advance

**Comment by duttapranab021** [comment]
done thanks

**Comment by savowe** [comment]
Does it work now?

**Comment by duttapranab021** [comment]
yes its working
